---
title: "Sentiment analysis in Folklore"
author: "Marina Ortín Fernández"
date: "17/9/2020"
output: html_document
---

# Librerías
```{r warning=FALSE}
library(tidytext)
library(dplyr)
library(kableExtra)
library(stringr)
library(ggplot2)
library(tidyr)
library(data.table)
library(gridExtra)
library(topicmodels)
library(openxlsx)
library(readxl)
library(textdata)
library(tidyverse)
library(stm)
library(quanteda)
library(wordcloud)
library(reshape2)
library(geometry)
library(Rtsne)
library(rsvd)
library(syuzhet)
```
# Data

```{r import}
data <-  read_excel("../data/folklore_lyrics.xlsx")
```

# Modelling

## Tracklist 

```{r echo = FALSE}
table <- data.frame(unique(data$song))
names(table) <- c("name of the song")
kable(table, caption = 'Table 1: Tracks in Folklore') %>%
  kable_styling('striped', full_width = F, position = 'center', latex_options = 'hold_position') %>%
  row_spec(0, color = 'white', background = 'darkcyan', align = 'c')
```


## Cleaning: stopwords

* Drop indicators (ie:[Verse 1])
* Drop meaningless words (ie: 'ooh', 'ah')

### Dictionary: Custom stopwords
```{r}
custom_stop_words <- bind_rows(tibble(word = c("ooh","ah"), lexicon = c("custom")), stop_words)
```

```{r}
data$lyrics <- str_remove_all(data$lyrics, pattern = regex("\\[(.*?)\\]"))
tidy_df <- data %>% 
  unnest_tokens(word, lyrics) %>% 
  anti_join(custom_stop_words, by = 'word')
tidy_df <- subset(tidy_df, !grepl("[0-9]", word))
```

## Analysis

### Most frequent words

```{r}
tidy_df %>%
  count(word, sort = TRUE) %>%
  filter(n > 10) %>%
  ggplot(aes(word, n)) +
  ggtitle("Figure 2: Most used words") +
  geom_col(fill = 'darkcyan') +
  xlab(NULL)
```

###Positive and negative words: Wordcloud

```{r}
negvspos <- tidy_df %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("deepskyblue3", "hotpink3"),
                   max.words = 100, scale=c(3.5,0.50))
```

### Topic modelling

```{r}
tswift_dfm <- tidy_df %>%
    count(song, word, sort = TRUE) %>%
    cast_dfm(song, word, n)

topic_model <- stm(tswift_dfm, K = 3, verbose = FALSE, init.type = "Spectral")
summary(topic_model)
```

### Words most likely to belong to a topic

```{r}
tswift_beta <- tidy(topic_model)

tswift_beta %>%
    group_by(topic) %>%
    top_n(10, beta) %>%
    ungroup() %>%
    mutate(topic = paste0("Topic ", topic),
           term = reorder_within(term, beta, topic)) %>%
    ggplot(aes(term, beta, fill = as.factor(topic))) +
    geom_col(alpha = 0.8, show.legend = FALSE) +
    scale_fill_viridis_d() +
    facet_wrap(~ topic, scales = "free_y",  ncol = 3) +
    coord_flip() +
    scale_x_reordered() +
    labs(x = NULL, y = expression(beta),
         title = "Words most likely to belong to a topic",
         subtitle = "Folklore")
```

### Emotion in songs

```{r}
lyrics <- as.character(tidy_df)
lyrics_sentiment <- get_nrc_sentiment((lyrics))
```

```{r}
sentimentscores <- data.frame(colSums(lyrics_sentiment[,]))   
names(sentimentscores) <- "Score"
sentimentscores <- cbind("sentiment" = rownames(sentimentscores), sentimentscores)

  ggplot(sentimentscores, aes(sentiment, Score)) +
  geom_bar(aes(fill = sentiment), stat = "identity", show.legend = FALSE) +
  scale_fill_viridis_d() + 
  labs(x = "Emotion & sentiment", y = "Scores", title = "Emotion in Taylor Swift songs")
```
#### Zoom-in: fear

```{r}
nrc_fear <- get_sentiments("nrc") %>% 
  filter(sentiment == "fear")

fear_words <- tidy_df %>%
    inner_join(nrc_fear) %>%
    count(word, sort = TRUE)
```

```{r}
fear_words %>% 
  kable(align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "condensed","responsive", "bordered")) %>%
  row_spec(0, background = 'lightpink3', color = "white", align = "c") %>%
  add_header_above(c("Words associated with fear in Taylor Swift songs"= 2), bold = TRUE)  %>% 
  scroll_box(width = "500px", height = "400px") 
```
#### Zoom-in: sadness

```{r}
nrc_sad <- get_sentiments("nrc") %>% 
  filter(sentiment == "sadness")

sad_words <- tidy_df %>%
    inner_join(nrc_sad) %>%
    count(word, sort = TRUE)
```

```{r}
sad_words %>% 
  kable(align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "condensed","responsive", "bordered")) %>%
  row_spec(0, background = 'lightpink3', color = "white", align = "c") %>%
  add_header_above(c("Words associated with sadness in Taylor Swift songs"= 2), bold = TRUE)  %>% 
  scroll_box(width = "500px", height = "400px") 
```
